### ISSUE TITLE
SQAlchemy session records not automatically purged

### ISSUE THREAD

**Issue by ckbaker10** [PowerDNS-Admin/PowerDNS-Admin#1483] opened 2023-03-28 07:54 UTC
### PDA version

0.4.0

### Python version

3.0

### Steps to Reproduce

Auto logout via expiry modal produces a session database entry with "expiry" NULL which in return produces a flask.session error that results in a 500 internal server error.

Using a working health check configuration produces a great amount of session entries overall, since there is no cleanup routine for database backed sessions.

```
*/1 * * * * /usr/bin/mysql -uroot --password=password -D powerdnsadmin -e 'delete from sessions where expiry is NULL;'
*/30 * * * * /usr/bin/mysql -uroot --password=password -D powerdnsadmin -e 'delete from sessions where expiry > NOW();'
```

### Expected Behavior

Sessions should have a cleanup procedure to be called periodically inside the docker

### Observed Behavior

No cleanup routine present
Auto expiry bug present

**Comment by ckbaker10** [comment] 2023-03-28 10:59
Can't find the right page I read it at, but basically it stated that flask session is supposed to run on Redis, which handles expiry by itself. 

Using sql as a session backend implicates housekeeping as an app task.

**Comment by heapdavid** [comment] 2023-11-24 10:20
We are seeing the same issue with sessions not being cleaned up when using postgresql as a backend, noticed as our db backups were taking longer and longer:

```
powerdns-admin=# SELECT pg_size_pretty( pg_total_relation_size('sessions') );
 pg_size_pretty
----------------
 4469 MB
```

Seems to be the same as https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1575 which looks like it was closed as stale

**Comment by ckbaker10** [comment] 2023-11-24 10:35
In my workaround, I had a mistake in the comparator.

`*/30 * * * * /usr/bin/mysql -uroot --password=password -D powerdnsadmin -e 'delete from sessions where expiry > NOW();'`

But yeah that bug is still live.

**Comment by AzorianMatt** [comment] 2023-11-24 10:42
I have a tiny bit of motivation and a small amount of free time this morning, so I will try to dig in and finally address this problem.

**Comment by AzorianMatt** [comment] 2023-11-24 11:33
@ckbaker10 @heapdavid I have committed a fix for this issue to the `dev` branch.

There are new issues with the dependency building again (fancy that!) which I must work out before the Docker image will successfully build again so keep your eyes peeled for an update to the `powerdnsadmin/pda-legacy:dev` image if you use Docker for deployment.

**Comment by AzorianMatt** [comment] 2023-11-24 12:10
This resolution is now available in the `powerdnsadmin/pda-legacy:dev` image and ready for you all to test resolution.

**Closed** 2023-11-24 15:25 UTC
Labels: bug / broken-feature, mod / accepted, mod / reviewed

**Comment by heapdavid** [comment] 2023-11-24 15:54
Hi,

I set up a fresh/test install to test this with the dev container, but can't create an initial admin user to test with

![image](https://github.com/PowerDNS-Admin/PowerDNS-Admin/assets/88432183/ad6a498e-73cf-42c4-b235-abc43867d8d4)

Looks like it's an SQLAlchemy-related error so may be related to the changes?

https://stackoverflow.com/questions/67997463/flask-sqlalchemy-query-relationship-attributeerror-neither-instrumentedattri

Thanks

**Comment by AzorianMatt** [comment] 2023-11-24 16:01
@heapdavid oh boy, it looks like another bug fix I accepted this morning is probably the cause of this. Give me a bit to reproduce and correct this. I'll let you know when the `dev` branch is ready again. My apologies!

**Comment by AzorianMatt** [comment] 2023-11-24 16:15
@heapdavid I just committed a fix for this bug to the `dev` branch so you can watch for when the new image is done building and pushed to Docker Hub. Sorry for the trouble!

**Comment by heapdavid** [comment] 2023-11-24 17:14
Thanks, that's resolved the account creation issue - how do i trigger the cleanup?

**Comment by AzorianMatt** [comment] 2023-11-24 17:22
@heapdavid you don't. It is triggered automatically on page requests during user routes I believe. My apologies, I'm not in front of my computer at the moment so I'm working off of memory here.

**Comment by heapdavid** [comment] 2023-11-24 17:26
Ah got it thanks - I thought that might be how it worked but it didn't seem to be working... until i created and logged in with a non-admin user, then the table has been cleared of any expired sessions 👍 

Thanks for sorting!

**Comment by AzorianMatt** [comment] 2023-11-24 17:30
@heapdavid you're welcome!

I realize the approach could probably be better, but it's just what I came up with and a matter of a few minutes that should generally resolve the issue.

Thanks for your participation in the matter!
