### ISSUE TITLE
No indication for unsaved changes

### ISSUE THREAD

**Issue by cseres3** [PowerDNS-Admin/PowerDNS-Admin#92] opened 2016-07-19 10:25 UTC
There is no indication if there are unsaved changes. If you edit records and forget to click "Apply Changes" button, all changes are lost and you don't get a warning or notification.

Expected results: clear indication of unsaved changes such as "Apply changes" button being gray by default if there are no unsaved changes and getting colour after changes. Possibly a warning if you try to browse to other page with unsaved changes.

**Comment by mathieumd** [comment] 2017-01-08 20:52
+1! Without such warning it's too easy to lost a lot of work. The edits should be highlighted (perhaps even a banner in the header with a summary of the waiting changes), and saved in a temporary buffer, so that the user could browser to other page and still get them when coming back to apply them.

The bottom line is that not a single edit/work of the user should be lost, at least not without a warning.

**Comment by sshipway** [comment] 2019-05-27 02:07
Yes, this should be a simple thing to add but would be soo useful.

**Comment by falz** [comment] 2021-02-08 13:29
Just encountered this while evaluating PowerDNS-Admin, possibly a showstopper for us. Logically, I would expect one of the two behaviors:

1) Changes apply when you hit save, have NO apply button at all.
2) If you don't apply, you get a popup message preventing you from navigating away due to this, and perhaps even a 'do you want to apply now' button there.

I haven't dug in to the technical reason that Apply is required, could someone enlighten me?

**Comment by sshipway** [comment] 2021-02-08 19:18
@falz Having the two-stage update (IE, you make the record changes, then Apply) makes sense because often you need to have a number of changes applied atomically.  For example, remove the old A record and replace it with a CNAME all in one go.  By having the Apply step, you can get everything looking right, then do one Apply action (and have one entry in the log).  Ideally, this would then also be able to be reverted at a single click in the log, though that feature is not yet available...
I can see why its a bit of a PITA to have the two-stage apply when making a single change, though.
As an aside, other systems (e.g. pfSense firewall) have a similar change-and-apply system.
Possibly, it could be a configuration switch to toggle behaviour between apply-immediately and two-stage-apply?

**Comment by wangibangi** [comment] 2021-02-08 19:22
In my eyes the problem is not really the two-stage-apply, but that it does not tell you if you have unapplied changes and discards all of them, when you leave the site without hitting "apply".

**Comment by falz** [comment] 2021-02-08 19:30
That example of a multiple stage apply makes sense to me. I'm not necessarily advocating for an apply-immediately, just trying to understand why, and that's sound reasoning.

Indeed, the issue is that you can navigate away without applying, without warning, and your changes are lost, and you may not notice, so definitely hoping something can be addressed with this part.

**Comment by sshipway** [comment] 2021-02-08 19:52
Yes, I do agree that it should be clearer when there are unapplied changes.  Possibly the 'apply changes' button shouldn't even be displayed if there's nothing pending, and when it is it should be in a nice big red banner with "Pending changes not yet applied: in it

**Comment by falz** [comment] 2021-02-23 15:57
Additional note when looking at this again: the code has some error checking warning if you hit apply before save, which shows a big red warning:

https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/powerdnsadmin/templates/domain.html#L207

Something equally scary (big red warning) seems ideal if one attempts to navigate away. 

OR possibly something in `button_save` put something less scary on screen to tell you to hit apply - less of a popup and more of an 'unsaved changes' warning somewhere.

https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/powerdnsadmin/templates/domain.html#L267

This is all sounds like javascript which is far out of my area of expertise.

**Comment by jbe-dw** [comment] 2022-04-25 15:13
Hello,

We are cleaning the issue tracker and closing your issue. You can follow the status here: #1178 

Regards
PowerDNS Admin Team

**Closed** 2023-06-22 14:42 UTC
