### ISSUE TITLE
LDAP Authentication Settings Validation / UX Issue

### ISSUE THREAD

**Issue by allahshukur-ahmadzada** [PowerDNS-Admin/PowerDNS-Admin#1402] opened 2023-02-24 16:47 UTC
Hi dear  team, I was trying to enable Ldap authentication with AD option, for a while all was fine I was trying different configurations to make AD work but suddenly I saw save button grayed out , if disable "Enable LDAP Authentication" I see button comes to normal and I can save but when I enable "Enable LDAP Authentication" again save button grayed out, there is some reason behind it? 

Just for you to know then I continued ldap config from database and was able to make it work, but still I cant do anychanges to it from UI.

**Comment by AzorianMatt** [comment] 2023-02-24 16:50
@allahshukur-ahmadzada I noticed this issue during my recent mobile-first upgrades of the UI. However, I found that it seemed to only be caused by particular validation scenarios so it seemed like it could be worked around using the UI (without direct modifications to the database).

I'll note this for a bug to be addressed though. Thanks for the report!

**Comment by jbe-dw** [comment] 2023-02-24 16:50
Hi,

There is a bug in the UI. You have to go to the AD tab and play with security features radio, as well as security in LDAP tab.
There is no easy way, from DB is the best alternative.

Regards

**Comment by AzorianMatt** [comment] 2023-04-11 23:33
@allahshukur-ahmadzada you should find this issue to be resolved with the latest release of `0.4.1` that came out today.

Resolved by #1515.

**Closed by AzorianMatt** 2023-04-11 23:33 UTC
Labels: bug / broken-feature, mod / accepted, mod / reviewed
