### ISSUE TITLE
LDAP Auth not working although DC says Login successful

### ISSUE THREAD

**Issue by mastermueller** [PowerDNS-Admin/PowerDNS-Admin#1196] opened 2022-05-18 09:55 UTC
Hi!
I have a problem with the newest docker image.
Previously we all logged in with LDAP.
Updated to the docker image from today (May 18 2022) -> cannot login with LDAP (Active Directory)
I can see the event id 4624 on my DC - successful login.
But powerdns says "User authentication failed".

I'll be happy to provide more info when needed.

Thank you!

**Comment by jbe-dw** [comment] 2022-05-19 12:01
Hello,

Can you check at docker logs if something is logged ?

Regards

**Comment by mastermueller** [comment] 2022-05-23 09:43
```
[2022-05-23 09:35:01,042] [user.py:164] ERROR - {'result': -7, 'desc': 'Bad search filter', 'ctrls': []}
[2022-05-23 09:35:01,042] [user.py:339] ERROR - LDAP group lookup for user "fas" has failed. Authentication request from 10.253.0.109
[2022-05-23 09:35:01,043] [index.py:546] WARNING - User fas failed to authenticate via LDAP from 10.253.0.109
```

DC says login successful:
![image](https://user-images.githubusercontent.com/99167007/169791814-c87ab726-e167-4947-92b9-120349a0fb5a.png)


Before the update the search filter worked, now it does not...

![image](https://user-images.githubusercontent.com/99167007/169791031-0b575c93-d3c2-4b3e-8c4a-e74b4b324d17.png)

**Comment by jbe-dw** [comment] 2022-05-23 13:11
Can you tell use which version of AD do you run ?

**Comment by mastermueller** [comment] 2022-05-23 13:16
It is a Windows Server 2012R2

![image](https://user-images.githubusercontent.com/99167007/169827879-693ddbac-7374-4599-994d-11363768cc9e.png)

**Comment by mastermueller** [comment] 2022-05-24 09:23
Sure, but I'm not exactly sure how.

BTW: When i untick the "Group Security" checkbox, the login works fine. Since we only have 3 users, it is ok for us to not use this feature.

**Comment by jbe-dw** [comment] 2022-05-24 09:52
Wrong answer, the change was merged because it is supposed to work with all platforms. The solution is to check wether it is your setup or the functionality and propose a fix.

You can check by running ldapsearch commands from a linux box:

`ldapsearch -H ldaps://your.ad -D "cn=admin,dc=yourcompany,dc=local" -W "(memberOf:1.2.840.113556.1.4.1941:=ADMIN_GROUP_DN)"`

You have to change the server Address, login DN (-D) and group DN (last part of filter to CN=RES-...) with the information you filled in PDA.

Let us know if it returns results or not

**Comment by jbe-dw** [comment] 2022-05-24 09:57
Checking at the code it may not work if you are in the User group.

Are you able to log in with an account in RES-DNS-Admins ?

**Comment by mastermueller** [comment] 2022-05-24 10:20
`ldapsearch -H ldap://10.250.1.21:389 -D "CN=Adminuser,OU=users,OU=XXXXX.local,DC=XXXXX,DC=local" -W "(memberOf:1.2.840.113556.1.4.1941:=CN=RES-DNS-Admins,OU=groups,OU=XXXXX.local,DC=XXXXX,DC=local)"`
returns:
```
# extended LDIF
#
# LDAPv3
# base <> (default) with scope subtree
# filter: (memberOf:1.2.840.113556.1.4.1941:=CN=RES-DNS-Admins,OU=groups,OU=XXXXX.local,DC=XXXXX,DC=local)
# requesting: ALL
#

# search result
search: 2
result: 32 No such object
text: 0000208D: NameErr: DSID-03100217, problem 2001 (NO_OBJECT), data 0, best 
 match of:
        ''


# numResponses: 1
```

When I enter a wrong password, I get "Invalid credentials", so it seems to accept my "-D" CN.

This is the group RES-DNS-Admins with 2 users:
![image](https://user-images.githubusercontent.com/99167007/170009370-f4595d4a-cc41-4b09-8f7e-9b66a1f000fb.png)


Login does not work with user from any group.

**Comment by mastermueller** [comment] 2022-05-24 11:35
When I add the base dn as you suggested, it seems to work!

```
# extended LDIF
#
# LDAPv3
# base <DC=XXXXX,DC=local> with scope subtree
# filter: (memberOf:1.2.840.113556.1.4.1941:=CN=RES-DNS-Admins,OU=groups,OU=XXXXX.local,DC=XXXXX,DC=local)
# requesting: ALL
#

# Fabian Schuetze, users, XXXXX.local, XXXXX.local
dn: CN=Fabian Schuetze,OU=users,OU=XXXXX.local,DC=XXXXX,DC=local
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: user
cn: Fabian Schuetze
sn: Schuetze
givenName: Fabian
distinguishedName: CN=Fabian Schuetze,OU=users,OU=XXXXX.local,DC=XXXXX,DC=loca
 l
instanceType: 4
whenCreated: 20110303134258.0Z
whenChanged: 20220521204137.0Z
displayName: Fabian Schuetze
uSNCreated: 16642
memberOf: CN=RES-DNS-Admins,OU=groups,OU=XXXXX.local,DC=XXXXX,DC=local
...a lot more groups...
uSNChanged: 15940400
name: Fabian Schuetze
objectGUID:: 9GYwapqQZkGg5tzGm3DIKA==
...a lot more attributes...

# search reference
ref: ldap://DomainDnsZones.XXXXX.local/DC=DomainDnsZones,DC=XXXXX,DC=local

# search reference
ref: ldap://ForestDnsZones.XXXXX.local/DC=ForestDnsZones,DC=XXXXX,DC=local

# search reference
ref: ldap://XXXXX.local/CN=Configuration,DC=XXXXX,DC=local

# search result
search: 2
result: 0 Success

# numResponses: 5
# numEntries: 1
# numReferences: 3
```

**Comment by jbe-dw** [comment] 2022-05-24 11:43
Ok this indicates that indeed your AD answers the query if it is formatted correctly.

I'll look at the code again this week, the filter is probably faulty.

Regards

**Comment by mastermueller** [comment] 2022-05-24 11:49
That sounds great, thank you! 👍 🥇

**Comment by jbe-dw** [comment] 2022-05-24 11:53
I can confirm it is broken. The filter is not ok.

**Closed** 2022-05-24 12:19 UTC
Labels: authentication

**Comment by jbe-dw** [comment] 2022-05-24 12:21
Please pull the newer version once it is published later this afternoon and confirm it is fixed.

Regards

**Comment by mastermueller** [comment] 2022-05-24 13:31
Just pulled the new docker container, LDAP auth with group security works like a charm now!

Thank you!! 👍 🥇
