### ISSUE TITLE
internal error (session issue)

### ISSUE THREAD

**Issue by fansari** [PowerDNS-Admin/PowerDNS-Admin#1508] opened 2023-04-06 09:58 UTC
### PDA version

0.4.0

### Python version

3.10.10

### Steps to Reproduce

I use docker version powerdnsadmin/pda-legacy:latest.

After some minutes doing nothing with the GUI I get an internal error of the web interface.

When I check the logs I get a traceback from which I concluded that something goes wrong in the sessions table.

After deleting the rows of the sessions table I can login again.

[session-error.log](https://github.com/PowerDNS-Admin/PowerDNS-Admin/files/11169171/session-error.log)

### Expected Behavior

No internal error after session time out.

### Observed Behavior

I get an internal server error and cannot relogin before clearing the sessions table.

**Comment by glomazdov** [comment] 2023-04-06 11:20
I have the same problem, but not in docker.
version 0.4
python 3.9
Systemd + Gunicorn + Nginx + PG
After clearing the session table everything is fine

**Comment by raunz** [comment] 2023-04-06 11:20
duplicate of #1439. resolved by #1461

**Closed** 2023-04-06 14:22 UTC
Labels: bug / broken-feature, mod / duplicate, mod / rejected
