### ISSUE TITLE
SVCB/HTTPS RR type support

### ISSUE THREAD

**Issue by PAStheLoD** [PowerDNS-Admin/PowerDNS-Admin#840] opened 2020-11-23 23:15 UTC
Hello!

First of all, thanks for this great admin UI!

So this is just a request/question about any information/plans regarding support for the new RR types coming to pdns auth 4.4, in particular about the HTTPS variant of the SVCB type, which is needed for managing and taking advantage of HTTP/3 (QUIC) eventually.

https://doc.powerdns.com/authoritative/upgrading.html#record-type-changes-on-secondaries
https://ypcs.fi/howto/2020/09/30/announce-https-via-dns/

Currently it's possible to add these records via the pdnsutil CLI, but they don't show up in the admin, and there's no way to enable it as far as I know.

Thanks for considering!

**Comment by jbe-dw** [comment] 2022-05-06 22:17
duplicate of #1168

**Closed by jbe-dw** 2022-05-06 22:17 UTC
Labels: duplicate
