### ISSUE TITLE
SQAlchemy session records not automatically purged

### ISSUE THREAD

**Issue by andrei-marinache** [PowerDNS-Admin/PowerDNS-Admin#1575] opened 2023-05-19 09:25 UTC
### PDA version

0.4.1

### Python version

3.10

### Steps to Reproduce

I have the following setup:

2 PDNS Admin instances, on 2 different servers, sharing the same MariaDB database (PDNS Admin runs in docker, powerdnsadmin/pda-legacy:0.4.0 - I've tested with 0.4.1 and it's the same thing)
2 HAproxy servers, each doing a healtcheck on each PDNS Admin server every 2 seconds (HTTP GET /)
Every time an HTTP GET / request is executed, an entry is created in PDNS DB, table sessions.

This translates into 2 queries * 2 HAProxy * 2 PDNS Admin servers / 2 (every 2 seconds) = 2 entries / second.
In 60 days the table got to about 10 million entries and the table takes up 3GB of disk space.

### Expected Behavior

Old sessions should be deleted from database, in order not to fill up the DB

### Observed Behavior

Old sessions are not deleted from database

**Comment by technischeHilfskraft** [comment] 2023-05-22 05:15
We can confirm the behaviour for 2 independent installations with 2 pods each in k8s.

**Comment by joek-office** [comment] 2023-06-12 06:31
Same thing here.
Is a workaround there or any perspective for bug fixing?

**Comment by AzorianMatt** [comment] 2023-11-24 11:34
@joek-office @hardoverflow @technischeHilfskraft @andrei-marinache I have committed a fix for this issue to the `dev` branch.

Dependency building is jacked up once again, so I'm working on getting that corrected in order for the Docker image to build automatically again.

**Comment by AzorianMatt** [comment] 2023-11-24 12:10
This issue is a duplicate of [issue 1483](https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1483). Closing.

**Closed by AzorianMatt** 2023-11-24 12:10 UTC
Labels: bug / broken-feature, mod / accepted, mod / reviewed
