### ISSUE TITLE
InvalidRequestError on re-login

### ISSUE THREAD

**Issue by rsaeks** [PowerDNS-Admin/PowerDNS-Admin#1493] opened 2023-03-29 20:20 UTC
### PDA version

0.4.0

### Python version

3.9

### Steps to Reproduce

1. Sign into PDA
2. Return about 30 minutes later

Additional notes: Restarting the PDA service allows for logging in again until the session re-expires.

### Expected Behavior

Ability to re-login error free

### Observed Behavior

I receive the following error message at the login page:

InvalidRequestError
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (MySQLdb._exceptions.IntegrityError) (1062, "Duplicate entry 'session:04377c07-7e9e-4e9f-8dfa-f836f5760c3b' for key 'session_id'")
[SQL: INSERT INTO sessions (session_id, data, expiry) VALUES (%s, %s, %s)]
[parameters: ('session:04377c07-7e9e-4e9f-8dfa-f836f5760c3b', b'\x80\x04\x95d\x00\x00\x00\x00\x00\x00\x00}\x94(\x8c\n_permanent\x94\x88\x8c\x0b_csrf_token\x94\x8c@90109c9a37887ef0b4a888db7b4b0ea2b55086d9333138497fcd786d93601d63\x94u.', datetime.datetime(2023, 3, 29, 20, 20, 45, 519720))]
(Background on this error at: http://sqlalche.me/e/13/gkpj) (Background on this error at: http://sqlalche.me/e/13/7s2a)

Traceback (most recent call last)
This is the Copy/Paste friendly version of the traceback.

`Traceback (most recent call last):
  File "/var/www/html/flask/lib/python3.9/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/www/html/flask/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/var/www/html/flask/lib/python3.9/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/var/www/html/flask/lib/python3.9/site-packages/flask/app.py", line 2072, in wsgi_app
    ctx.push()
  File "/var/www/html/flask/lib/python3.9/site-packages/flask/ctx.py", line 434, in push
    self.session = session_interface.open_session(self.app, self.request)
  File "/var/www/html/flask/lib/python3.9/site-packages/flask_session/sessions.py", line 533, in open_session
    saved_session = self.sql_session_model.query.filter_by(
  File "/var/www/html/flask/lib64/python3.9/site-packages/sqlalchemy/orm/query.py", line 3429, in first
    ret = list(self[0:1])
  File "/var/www/html/flask/lib64/python3.9/site-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__
    return list(res)
  File "/var/www/html/flask/lib64/python3.9/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/var/www/html/flask/lib64/python3.9/site-packages/sqlalchemy/orm/query.py", line 3556, in _execute_and_instances
    conn = self._get_bind_args(
  File "/var/www/html/flask/lib64/python3.9/site-packages/sqlalchemy/orm/query.py", line 3571, in _get_bind_args
    return fn(
  File "/var/www/html/flask/lib64/python3.9/site-packages/sqlalchemy/orm/query.py", line 3550, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/var/www/html/flask/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 1142, in connection
    return self._connection_for_bind(
  File "/var/www/html/flask/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 1150, in _connection_for_bind
    return self.transaction._connection_for_bind(
  File "/var/www/html/flask/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 409, in _connection_for_bind
    self._assert_active()
  File "/var/www/html/flask/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 289, in _assert_active
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (MySQLdb._exceptions.IntegrityError) (1062, "Duplicate entry 'session:04377c07-7e9e-4e9f-8dfa-f836f5760c3b' for key 'session_id'")
[SQL: INSERT INTO sessions (session_id, data, expiry) VALUES (%s, %s, %s)]
[parameters: ('session:04377c07-7e9e-4e9f-8dfa-f836f5760c3b', b'\x80\x04\x95d\x00\x00\x00\x00\x00\x00\x00}\x94(\x8c\n_permanent\x94\x88\x8c\x0b_csrf_token\x94\x8c@90109c9a37887ef0b4a888db7b4b0ea2b55086d9333138497fcd786d93601d63\x94u.', datetime.datetime(2023, 3, 29, 20, 20, 45, 519720))]
(Background on this error at: http://sqlalche.me/e/13/gkpj) (Background on this error at: http://sqlalche.me/e/13/7s2a)`

**Comment by AzorianMatt** [comment] 2023-03-29 22:55
Duplicate of #1439. Please read the contribution guidelines.

**Closed** 2023-03-29 22:56 UTC
Labels: bug / broken-feature, mod / duplicate, mod / rejected, mod / reviewed
